# frozen_string_literal: true

# https://github.com/Homebrew/homebrew-bundle

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'

# Homebrew
# https://github.com/Homebrew/brew/

# Need to install openssl before libyaml
brew 'openssl'
brew 'openssl@1.1' # wget dependency

brew 'autoconf' # asdf dependency
brew 'automake' # asdf dependency
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'cmake'
brew 'coreutils'
brew 'exa'
brew 'gh' # github cli
brew 'git'
brew 'git-quick-stats'
brew 'gnupg' # asdf-nodejs dependency
brew 'htop'
brew 'less'
brew 'libtool' # asdf dependency
brew 'libxslt' # asdf dependency
brew 'libyaml' # asdf dependency
brew 'mas'
brew 'pgcli'
brew 'pstree'
brew 'python3'
brew 'readline'
brew 'redis'
brew 'rsync'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'starship'
brew 'tree'
brew 'unixodbc' # asdf dependency
brew 'wget'
brew 'zsh'

# homebrew-cask
# https://github.com/caskroom/homebrew-cask
#cask '1password'
cask 'alfred'
cask 'docker-toolbox'
cask 'dropbox'
cask 'font-caskaydia-cove-nerd-font'
cask 'font-fira-code-nerd-font'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-victor-mono-nerd-font'
cask 'github'
cask 'gitify'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
#cask 'loom'
#cask 'microsoft-teams'
cask 'ngrok'
#cask 'pgadmin4'
cask 'postman'
cask 'rubymine'
#cask 'runcat'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'whatsapp'

# mas "Keynote", id: 409183694
# mas "Runcat"
# vim: set filetype=ruby:
