[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -s main-alacritty"]


[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 1 }
dynamic_padding = true
opacity = 0.8
blur = true
decorations = "Buttonless"
startup_mode = "Fullscreen"

[font]
size = 14.0
[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    # opt + right and left jump between words
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
    # ⌘ + d adds a pane to the right (splits window vertically)
    { key = "D",  mods = "Command", chars = "\u0002%" },
    # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
    { key = "D",  mods = "Command|Shift", chars = "\u0002\"" },
    # ⌘ + w prompts you to close the pane, "y" to confirm
    { key = "W",  mods = "Command", chars = "\u0002x" },
    # ⌘ + arrows are for directional navigation around the panes
    # move down a pane
    { key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
    # move up a pane
    { key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
     # move left a pane
    { key = "Left", mods = "Command", chars = "\u0002\u001b[D" },
    # move right a pane
    { key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
    # ⌘ + ⇧ + enter maximizes the pane within the alacritty window
    { key = "Enter", mods = "Command|Shift", chars = "\u0002z" },
]
