# https://starship.rs/config/
format = "$all"

add_newline = false
command_timeout = 2000

#[package]
#disabled = true

[directory]
style = "bold blue"

[git_branch]
style = "bold bright-white"

[git_status]
ahead = "[](purple)[$count](white)"
behind = "[](cyan)[$count](white)"
conflicted = '[=$count](yellow)'
deleted = '[✘$count](black)'
diverged = "[](cyan)[$ahead_count](white)[](purple)[$behind_count](white)"
modified = '[*$count](red)'
renamed = "[»$count](purple)"
staged = "[+$count](green)"
stashed = "[\\$$count](yellow)"
style = "bold bright-white"
untracked = "[?$count](cyan)"

[git_commit]
only_detached = true
style = "bold black"
format = "[$hash]($style) "

[ruby]
symbol = " "
style = "bold red"
format = '\[[$symbol($version)]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "

[aws]
symbol = "󰸏 "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
[aws.region_aliases]
eu-central-1 = 'frankfurt'

[docker_context]
symbol = "󰡨 "
format = '\[[$symbol$context]($style)\]'

